<?php
// module/AdManager/view/ad-manager/ad-manager/index.phtml:
 
$title = 'My ads';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('ad-manager', array('action'=>'add'));?>">Add new ad</a>
</p>
 
<table class="table">
<tr>
    <th>Creation Date</th>
    <th>Publisher ID</th>
    <th>Publisher</th>
    <th>&nbsp;</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($ads as $ad) : ?>
<tr>
    <td><?php echo $ad->creation_date->format('Y-m-d H:i:s');?></td>
    <td><?php echo $this->escapeHtml($ad->publisher_id);?></td>
    <td><?php var_export($ad);?></td>
    <td>
        <a href="<?php echo $this->url('ad-manager',
            array('action'=>'edit', 'id' => $ad->id));?>">Edit</a>
        <a href="<?php echo $this->url('ad-manager',
            array('action'=>'delete', 'id' => $ad->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>


